org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.java.installations.paths=/Users/lucasbuckley/Library/Application Support/PrismLauncher/java/java-runtime-delta

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.233
neo_version_range=[21.1.233,)
loader_version_range=[4,)

mod_id=labdimension
mod_name=Lab Dimension
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.inferno.labdimension
mod_authors=Inferno
mod_description=Toggle between your current dimension and a personal creative lab dimension.
