package com.inferno.labdimension.dimension;

import net.minecraft.core.HolderLookup;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.ListTag;
import net.minecraft.nbt.StringTag;
import net.minecraft.nbt.Tag;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.saveddata.SavedData;

import javax.annotation.Nullable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;

public final class LabRosterData extends SavedData {

    /** Sentinel meaning "never recorded" -- the very first boot after this mod is
     *  installed must not treat that as a min_y change and mass-regenerate labs
     *  that don't exist yet. */
    public static final int UNKNOWN_MIN_Y = Integer.MIN_VALUE;

    private final Map<UUID, LabSettings> entries = new HashMap<>();
    private final List<ResourceLocation> pendingDeletion = new ArrayList<>();
    private int worldMinY = UNKNOWN_MIN_Y;

    public static LabRosterData get(ServerLevel overworld) {
        SavedData.Factory<LabRosterData> factory = new SavedData.Factory<>(
                LabRosterData::new,
                (tag, provider) -> load(tag),
                null
        );
        return overworld.getDataStorage().computeIfAbsent(factory, "labdimension_roster");
    }

    /** Creates a roster entry if absent. Use for explicit lab creation only --
     *  everything else (invite lookups, WorldEdit predicate, etc.) must use
     *  peek() so a player without a lab doesn't silently get one created. */
    public LabSettings entryFor(UUID owner) {
        return entries.computeIfAbsent(owner, id -> {
            LabSettings s = new LabSettings();
            s.createdAt = System.currentTimeMillis();
            setDirty();
            return s;
        });
    }

    /** Non-creating lookup. Null if this player has no lab. */
    public @Nullable LabSettings peek(UUID owner) {
        return entries.get(owner);
    }

    /** Explicit creation entry point for /lab create. */
    public LabSettings create(UUID owner) {
        return entryFor(owner);
    }

    /** Wholesale replace, used by LabLifecycle.replace once a new LabSettings
     *  (bumped generation, new creation-time fields) has been built. */
    public void replaceEntry(UUID owner, LabSettings settings) {
        entries.put(owner, settings);
        setDirty();
    }

    public boolean has(UUID owner) {
        return entries.containsKey(owner);
    }

    public void forget(UUID owner) {
        entries.remove(owner);
        setDirty();
    }

    public Set<UUID> allOwners() {
        return Set.copyOf(entries.keySet());
    }

    public Set<UUID> publicOwners() {
        Set<UUID> out = new HashSet<>();
        for (Map.Entry<UUID, LabSettings> e : entries.entrySet()) {
            if (e.getValue().visibility == LabSettings.Visibility.PUBLIC) {
                out.add(e.getKey());
            }
        }
        return out;
    }

    public List<ResourceLocation> pendingDeletion() {
        return List.copyOf(pendingDeletion);
    }

    public void addPendingDeletion(ResourceLocation dimensionId) {
        pendingDeletion.add(dimensionId);
        setDirty();
    }

    public void clearPendingDeletion(ResourceLocation dimensionId) {
        pendingDeletion.remove(dimensionId);
        setDirty();
    }

    public int getWorldMinY() {
        return worldMinY;
    }

    public void setWorldMinY(int minY) {
        worldMinY = minY;
        setDirty();
    }

    private static LabRosterData load(CompoundTag tag) {
        LabRosterData data = new LabRosterData();
        ListTag list = tag.getList("owners", Tag.TAG_COMPOUND);
        for (int i = 0; i < list.size(); i++) {
            CompoundTag ownerTag = list.getCompound(i);
            UUID owner = ownerTag.getUUID("owner");
            data.entries.put(owner, loadEntry(ownerTag));
        }
        ListTag deletions = tag.getList("pendingDeletion", Tag.TAG_STRING);
        for (int i = 0; i < deletions.size(); i++) {
            data.pendingDeletion.add(ResourceLocation.parse(deletions.getString(i)));
        }
        data.worldMinY = tag.contains("worldMinY") ? tag.getInt("worldMinY") : UNKNOWN_MIN_Y;
        return data;
    }

    private static LabSettings loadEntry(CompoundTag ownerTag) {
        if (ownerTag.contains("v") && ownerTag.getInt("v") >= 2) {
            return LabSettings.load(ownerTag);
        }
        // Legacy v1 Entry: { platformGenerated, createdAt, invited: [uuid, ...] }.
        // Every v1 lab was generated by FlatLevelSource with zero layers, so it MUST
        // be tagged VOID here -- defaulting to SUPERFLAT would generate stone into
        // any newly-explored chunk of an existing lab and leave a visible seam.
        LabSettings s = new LabSettings();
        s.worldType = LabSettings.WorldType.VOID;
        s.visibility = LabSettings.Visibility.PRIVATE;
        s.guestPermission = LabSettings.GuestPermission.WORLDEDIT;
        s.generation = 0;
        s.platformGenerated = ownerTag.getBoolean("platformGenerated");
        s.createdAt = ownerTag.getLong("createdAt");
        ListTag invited = ownerTag.getList("invited", Tag.TAG_STRING);
        for (int j = 0; j < invited.size(); j++) {
            try {
                s.whitelist.add(UUID.fromString(invited.getString(j)));
            } catch (IllegalArgumentException ignored) {
                // corrupt entry -- skip
            }
        }
        return s;
    }

    @Override
    public CompoundTag save(CompoundTag tag, HolderLookup.Provider provider) {
        ListTag list = new ListTag();
        for (Map.Entry<UUID, LabSettings> e : entries.entrySet()) {
            CompoundTag ownerTag = e.getValue().save();
            ownerTag.putUUID("owner", e.getKey());
            list.add(ownerTag);
        }
        tag.put("owners", list);

        ListTag deletions = new ListTag();
        for (ResourceLocation id : pendingDeletion) {
            deletions.add(StringTag.valueOf(id.toString()));
        }
        tag.put("pendingDeletion", deletions);
        tag.putInt("worldMinY", worldMinY);
        return tag;
    }
}
